version: '3.1'
services:
  enfermedades-back:
    image: andresyusty/enfermedades-back
    container_name: enfermedades-back
    restart: always
    build: 
      context: ./
    ports:  
    - "8282:8282"
    depends_on:
      - enfermedades-db
    networks:
    - network_enfermedades

  enfermedades-db:
    image: mysql:8.0
    container_name: enfermedades-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:  
    - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yusty123
    networks:
    - network_enfermedades
    
networks:
  network_enfermedades:
     external: true
